### PR TITLE
Add limit for number of reviews

### PR DESCRIPTION
**Pull request by mahotilo**

### CODE REVIEW

**Comment by sharoncreech** [comment]
Tested and  got error

> PHP Parse error:  syntax error, unexpected 'continue' (T_CONTINUE) on line 86

**Comment by mahotilo** [comment]
Could you check it again?

**Comment by sharoncreech** [comment]
Tested and works. Only if 0 is set, as it is set by default then it show 8. If you chose 3 or 5 or any other numbers then is everything alright.

**Comment by gaffling** [comment]
Nice, thanks!

**Pull request merged**
